# Generated by Django 3.0.4 on 2020-04-04 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10baa23d-43a5-4b4a-ad96-ffc516ee6424'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10baa23d-43a5-4b4a-ad96-ffc516ee6424'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10baa23d-43a5-4b4a-ad96-ffc516ee6424'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10baa23d-43a5-4b4a-ad96-ffc516ee6424'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaluseraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10baa23d-43a5-4b4a-ad96-ffc516ee6424'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
