# Generated by Django 3.0.4 on 2020-04-05 16:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200405_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('650b7c73-ccd0-45e8-ba70-bb009e12aae4'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('650b7c73-ccd0-45e8-ba70-bb009e12aae4'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('650b7c73-ccd0-45e8-ba70-bb009e12aae4'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('650b7c73-ccd0-45e8-ba70-bb009e12aae4'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaluseraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('650b7c73-ccd0-45e8-ba70-bb009e12aae4'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
