# Generated by Django 3.0.4 on 2020-04-05 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200405_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='core.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ace6a41f-f218-457a-88f0-e4701b17f193'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ace6a41f-f218-457a-88f0-e4701b17f193'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ace6a41f-f218-457a-88f0-e4701b17f193'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ace6a41f-f218-457a-88f0-e4701b17f193'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaluseraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ace6a41f-f218-457a-88f0-e4701b17f193'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
