# Generated by Django 3.0.4 on 2020-04-05 20:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200405_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contacts',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='core.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9298425e-25b1-41b3-a702-9e107582c01f'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9298425e-25b1-41b3-a702-9e107582c01f'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9298425e-25b1-41b3-a702-9e107582c01f'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9298425e-25b1-41b3-a702-9e107582c01f'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaluseraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9298425e-25b1-41b3-a702-9e107582c01f'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
