# Generated by Django 3.1.2 on 2020-10-26 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200405_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b459a77b-0d31-4b9e-bd80-565c889309d6'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b459a77b-0d31-4b9e-bd80-565c889309d6'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b459a77b-0d31-4b9e-bd80-565c889309d6'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b459a77b-0d31-4b9e-bd80-565c889309d6'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaluseraccount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='externaluseraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b459a77b-0d31-4b9e-bd80-565c889309d6'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaluseraccount',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.externalsystem'),
        ),
    ]
